### ISSUE TITLE
Webpage sort not working

### ISSUE THREAD

**Issue by Jurgenn22** [HugoGresse/hacs-repositories#10]
Hello,
The sort function on the webpage for newest, most stars is not working anymore.

**Comment by HugoGresse** [comment]
Thanks for the info. I'll fix it ASAP.

**Comment by HugoGresse** [comment]
Fixed... was using the old token format from github....

**Comment by Jurgenn22** [comment]
> Fixed... was using the old token format from github....

Thx!
