### ISSUE TITLE
Can't find air-visual-card

### ISSUE THREAD

**Issue by nardev** [HugoGresse/hacs-repositories#9]
I can't find "air-visual-card" on the list and when i try adding it manually it says it's already added.

What's going on there?

**Comment by HugoGresse** [comment]
🤔 it's right there: 
![Capture d’écran 2021-03-23 à 10 51 04](https://user-images.githubusercontent.com/662377/112127468-c41d3a00-8bc5-11eb-9d85-1eb5c36e66c9.png)

**Comment by HugoGresse** [comment]
Closing this but feel free to reopen one if something happen. 
HAC Repositories is just a way to browse HACS Repo without Home Assistant, this is not where the repositories are stored

**Comment by nardev** [comment]
What am i doing wrong :(?

![Screenshot from 2021-03-23 11-17-19](https://user-images.githubusercontent.com/696054/112131038-64c12900-8bc9-11eb-8c2b-70c80ee1a024.png)

**Comment by HugoGresse** [comment]
as I sayed, this repositories is NOT the official HACS repo and does not offer support for HACS repositories. 
You better looked at : 
- official website: https://hacs.xyz/
- their discord server: https://discord.gg/apgchf8

**Comment by nardev** [comment]
sorry
